title: Blog of Qian Luo
description: Hi,I'm here.I'm a web front end developer.

baseurl: "http://roseluo.com/blog"
url: "http://roseluo.com"

github_username:  AzureRay

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
